export const ADMIN_API_URLS = {
    ADMIN_ADD_NEW_CATEGORY: "/api/Category/addNewCategory",
    ADMIN_GET_ALL_CATEGORIES: "/api/Category/GetAllCategory",
    ADMIN_GET_SINGLE_CATEGORY:"/api/Category/singleCategory",
    ADMIN_DELETE_SINGLE_CATEGORY:"/api/Category/deleteCategory",
    ADMIN_UPDATE_SINGLE_CATEGORY:"/api/Category/updateCategory",
    ADMIN_ADD_NEW_COURSE:"/api/Course/AddNewCourse",
    ADMIN_GET_ALL_COURSE:"/api/Course/paged",
    ADMIN_GET_SINGLE_COURSE_BY_ID:"/api/Course/GetSingleCourse",
    ADMIN_UPDATE_SINGLE_COURSE_BY_ID:"/api/Course/updateCourse",
    ADMIN_DELETE_SINGLE_COURSE_BY_ID:"/api/Course/removeCourse",
    ADMIN_GET_ALL_COURSES:"/api/Course/GetAllCourse",
    ADMIN_ADD_HOME_SLIDER:"/api/HomeSlider",
    ADMIN_GET_ALL_SLIDER:"/api/HomeSlider/GetAllSlider",
    ADMIN_GET_SLIDER_BY_ID:"/api/HomeSlider/GetSingleSlider",
    ADMIN_DELETE_SLIDER_BY_ID:"/api/HomeSlider/DeleteSliderById",
    ADMIN_UPDATE_SLIDER_BY_ID:"/api/HomeSlider/UpdateSlider",
    ADMIN_ADD_NEW_COUNTRY:"/api/AdminCountryState/addNewCountry",
    ADMIN_ADD_NEW_STATE:"/api/AdminCountryState/addNewState",
    ADMIN_GET_ALL_COUNTRY:"/api/AdminCountryState/getAllCountry",
    ADMIN_GET_ALL_STATES:"/api/AdminCountryState/getAllState",
    ADMIN_GET_SINGLE_COUNTRY_BY_ID:"/api/AdminCountryState/getCountry",
    ADMIN_GET_SINGLE_STATE_BY_ID:"/api/AdminCountryState/getState",
    ADMIN_UPDATE_SINGLE_COUNTRY_BY_ID:"/api/AdminCountryState/updateCountry",
    ADMIN_UPDATE_SINGLE_STATE_BY_ID:"/api/AdminCountryState/updateState",
    ADMIN_DELETE_COUNTRY_BY_ID:"/api/AdminCountryState/deleteCountry",
    ADMIN_DELETE_STATE_BY_ID:"/api/AdminCountryState/deleteState",
}